### ISSUE TITLE
Android App Problem

### ISSUE THREAD

**Issue by onuryurtturk** [EricssonResearch/openwebrtc-examples#109]
Android Native Call Example giving NullpointerException how can  I handle this? 

Logs :    

06-30 12:20:24.151      342-342/com.ericsson.research.owr.examples.nativecall D/NativeCall﹕ onJoinClicked
06-30 12:20:24.206      342-342/com.ericsson.research.owr.examples.nativecall W/libOpenSLES﹕ Leaving Object::GetInterface (SL_RESULT_FEATURE_UNSUPPORTED)
06-30 12:20:24.216      342-342/com.ericsson.research.owr.examples.nativecall D/NativeCall﹕ setting self-view: android.view.TextureView{42a7dc58 V.ED..C. ......ID 662,542-1046,830 #7f060008 app:id/self_view}
06-30 12:20:24.706      342-517/com.ericsson.research.owr.examples.nativecall I/System.out﹕ Thread-13890 calls detatch()
06-30 12:20:24.706      342-342/com.ericsson.research.owr.examples.nativecall W/EventSource﹕ unhandled event: busy
06-30 12:20:24.721      342-342/com.ericsson.research.owr.examples.nativecall D/NativeCall﹕ stopping self-view
06-30 12:20:24.721      342-342/com.ericsson.research.owr.examples.nativecall D/AndroidRuntime﹕ Shutting down VM
06-30 12:20:24.721      342-342/com.ericsson.research.owr.examples.nativecall W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41868c08)
06-30 12:20:24.721      342-342/com.ericsson.research.owr.examples.nativecall E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.ericsson.research.owr.examples.nativecall, PID: 342
    java.lang.NullPointerException
            at com.ericsson.research.owr.examples.nativecall.NativeCallExampleActivity.onDisconnect(NativeCallExampleActivity.java:338)
            at com.ericsson.research.owr.examples.nativecall.SignalingChannel$1$1.run(SignalingChannel.java:120)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5356)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)
06-30 12:20:24.881      342-359/com.ericsson.research.owr.examples.nativecall D/Camera﹕ app passed NULL surface
06-30 12:20:25.386      342-359/com.ericsson.research.owr.examples.nativecall D/Camera﹕ app passed NULL surface
06-30 12:20:25.501      342-359/com.ericsson.research.owr.examples.nativecall I/g_log﹕ _owr_media_source_release_source: assertion 'GST_IS_ELEMENT(source)' failed
06-30 12:20:25.871      342-359/com.ericsson.research.owr.examples.nativecall I/gst_log﹕ 0x78399f80 ERROR   default jni/android_video_capture_device.c:2504:VCD_unprepare: jni/android_video_capture_device.c VCD_unprepare ERROR: illegal state (4)
06-30 12:20:25.871      342-359/com.ericsson.research.owr.examples.nativecall E/gstandroidvideosrc﹕ jni/android_video_capture_device.c VCD_unprepare ERROR: illegal state (4)
06-30 12:20:25.871      342-359/com.ericsson.research.owr.examples.nativecall I/gst_log﹕ 0x78399f80 ERROR   gstandroidvideosrc jni/gst_android_video_source.c:248:gst_android_video_source_change_state: gst_android_video_source_change_state: ERROR: Could not change state
06-30 12:20:25.871      342-359/com.ericsson.research.owr.examples.nativecall E/gstandroidvideosrc﹕ gst_android_video_source_change_state: ERROR: Could not change state
06-30 12:20:25.871      342-359/com.ericsson.research.owr.examples.nativecall I/gst_log﹕ 0x78399f80 ERROR   default jni/android_video_capture_device.c:2504:VCD_unprepare: jni/android_video_capture_device.c VCD_unprepare ERROR: illegal state (4)
06-30 12:20:25.871      342-359/com.ericsson.research.owr.examples.nativecall E/gstandroidvideosrc﹕ jni/android_video_capture_device.c VCD_unprepare ERROR: illegal state (4)
06-30 12:20:25.871      342-359/com.ericsson.research.owr.examples.nativecall I/gst_log﹕ 0x78399f80 ERROR   gstandroidvideosrc jni/gst_android_video_source.c:248:gst_android_video_source_change_state: gst_android_video_source_change_state: ERROR: Could not change state
06-30 12:20:25.871      342-359/com.ericsson.research.owr.examples.nativecall E/gstandroidvideosrc﹕ gst_android_video_source_change_state: ERROR: Could not change state
06-30 12:20:26.366      342-671/com.ericsson.research.owr.examples.nativecall D/dalvikvm﹕ threadid=12: thread exiting, not yet detached (count=0)

**Comment by superdump** [comment]
@Rugvip ?
