### ISSUE TITLE
couldn't build on ubuntu 14.04

### ISSUE THREAD

**Issue by KensakuKOMATSU** [EricssonResearch/openwebrtc-examples#111]
I tried to build openwebrtc on ubuntu 14.04, but it failed for buildpackage step

*running step*
```
$ ./cerbero-uninstalled -c config/linux.cbc package -f openwebrtc
```

*error message*

it seems to me that the error has occurred for the dependency trouble of libcairo.so.2

```
dpkg-shlibdeps: error: no dependency information found for /opt/openwebrtc-0.3/lib/libcairo.so.2 (used by debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstgtksink.so)
dh_shlibdeps: dpkg-shlibdeps -Tdebian/openwebrtc-gstreamer-1.0-core.substvars debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libopus.so.0.5.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libnice.so.10.6.2 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstsdp-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstapp-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libsrtp.so.1 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libopenh264.so.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstdtls.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstalaw.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstaudioconvert.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstnice.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstopus.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgsttypefindfunctions.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstudp.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvpx.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstrtp.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstpulse.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideoconvert.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstapp.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstopenh264.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstaudioresample.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideo4linux2.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstaudiotestsrc.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideofilter.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstmulaw.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstinter.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstrtpmanager.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstgtksink.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvolume.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideoparsersbad.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstaudiorate.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideoscale.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideorate.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstopengl.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstsrtp.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideocrop.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstcoreelements.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideotestsrc.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstnet-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstvideo-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstbadvideo-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstreamer-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstaudio-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstrtsp-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstcodecparsers-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstbase-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstpbutils-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstbadbase-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstriff-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstfft-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstcontroller-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libvpx.so.2.0.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstcheck-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstgl-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstrtp-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstallocators-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgsttag-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/libexec/gstreamer-1.0/gst-plugin-scanner debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/bin/gst-typefind-1.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/bin/gst-discoverer-1.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/bin/gst-play-1.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/bin/gst-inspect-1.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/bin/gst-launch-1.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/bin/gst-device-monitor-1.0 returned exit code 2
make: *** [binary-arch] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
Traceback (most recent call last):
  File "./cerbero/main.py", line 105, in run_command
    res = commands.run(command, self.config, self.args)
  File "./cerbero/commands/__init__.py", line 78, in run
    return _commands[command].run(config, args)
  File "./cerbero/commands/package.py", line 97, in run
    args.force, args.keep_temp)
  File "./cerbero/packages/linux.py", line 57, in pack
    self.pack_deps(output_dir, tmpdir, force)
  File "./cerbero/packages/linux.py", line 115, in pack_deps
    packager.pack(output_dir, self.devel, force, True, True, tmpdir)
  File "./cerbero/packages/linux.py", line 78, in pack
    paths = self.build(output_dir, tarname, tmpdir, packagedir, srcdir)
  File "./cerbero/packages/debian.py", line 282, in build
    shell.call('dpkg-buildpackage -rfakeroot -us -uc -D -b', srcdir)
  File "./cerbero/utils/shell.py", line 157, in call
    raise FatalError(_("Error running command: %s") % cmd)
FatalError: Fatal Error: Error running command: dpkg-buildpackage -rfakeroot -us -uc -D -b
***** Error running 'package' command:
Fatal Error: Error running command: dpkg-buildpackage -rfakeroot -us -uc -D -b
usage: cerbero-uninstalled [-h] [-c CONFIG]
                           {add-recipe,rdeps,tag,genxcconfig,genlibfiles,check,list-packages,show-config,add-package,build,genvsprops,shell,run,cleanone,packageinfo,buildone,wipe,debug-packages,package,bootstrap,list,checkpackage,deps,gensdkshell,fetch-package,fetch}
```

*system info*

```
$ uname -a
Linux ubuntu 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

could you give me any help?

**Comment by superdump** [comment]
This should work around the issue for now, but I have not had time to think if it is the right fix and therefore have not committed it. Apologies for the inconvenience.

```diff
diff --git a/config/linux.config b/config/linux.config
index 27bd9a5..50551d4 100644
--- a/config/linux.config
+++ b/config/linux.config
@@ -6,6 +6,8 @@
 import os
 from cerbero.config import Architecture

+variants += ['nogtk3']
+
 if 'noalsa' not in variants:
     variants.append('alsa')
 if 'nox11' not in variants:
```

**Comment by KensakuKOMATSU** [comment]
thx for your quick response ;-)

However .... I found another error for ``libjpeg.so.8`` while ``libcairo.so.2`` issue seems fixed based on your patch.

```
dh_shlibdeps -a
dpkg-shlibdeps: error: no dependency information found for /opt/openwebrtc-0.3/lib/libjpeg.so.8 (used by debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstopengl.so)
dh_shlibdeps: dpkg-shlibdeps -Tdebian/openwebrtc-gstreamer-1.0-core.substvars debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libopus.so.0.5.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libnice.so.10.6.2 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstsdp-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstapp-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libsrtp.so.1 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libopenh264.so.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstdtls.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstalaw.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstaudioconvert.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstnice.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstopus.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgsttypefindfunctions.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstudp.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvpx.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstrtp.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstpulse.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideoconvert.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstapp.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstopenh264.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstaudioresample.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideo4linux2.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstaudiotestsrc.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideofilter.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstmulaw.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstinter.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstrtpmanager.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvolume.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideoparsersbad.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstaudiorate.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideoscale.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideorate.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstopengl.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstsrtp.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideocrop.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstcoreelements.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideotestsrc.so debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstnet-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstvideo-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstbadvideo-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstreamer-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstaudio-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstrtsp-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstcodecparsers-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstbase-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstpbutils-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstbadbase-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstriff-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstfft-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstcontroller-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libvpx.so.2.0.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstcheck-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstgl-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstrtp-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgstallocators-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/lib/libgsttag-1.0.so.0.502.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/libexec/gstreamer-1.0/gst-plugin-scanner debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/bin/gst-typefind-1.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/bin/gst-discoverer-1.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/bin/gst-play-1.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/bin/gst-inspect-1.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/bin/gst-launch-1.0 debian/openwebrtc-gstreamer-1.0-core/opt/openwebrtc-0.3/bin/gst-device-monitor-1.0 returned exit code 2
make: *** [binary-arch] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
Traceback (most recent call last):
  File "./cerbero/main.py", line 105, in run_command
    res = commands.run(command, self.config, self.args)
  File "./cerbero/commands/__init__.py", line 78, in run
    return _commands[command].run(config, args)
  File "./cerbero/commands/package.py", line 97, in run
    args.force, args.keep_temp)
  File "./cerbero/packages/linux.py", line 57, in pack
    self.pack_deps(output_dir, tmpdir, force)
  File "./cerbero/packages/linux.py", line 115, in pack_deps
    packager.pack(output_dir, self.devel, force, True, True, tmpdir)
  File "./cerbero/packages/linux.py", line 78, in pack
    paths = self.build(output_dir, tarname, tmpdir, packagedir, srcdir)
  File "./cerbero/packages/debian.py", line 282, in build
    shell.call('dpkg-buildpackage -rfakeroot -us -uc -D -b', srcdir)
  File "./cerbero/utils/shell.py", line 157, in call
    raise FatalError(_("Error running command: %s") % cmd)
FatalError: Fatal Error: Error running command: dpkg-buildpackage -rfakeroot -us -uc -D -b
***** Error running 'package' command:
Fatal Error: Error running command: dpkg-buildpackage -rfakeroot -us -uc -D -b
usage: cerbero-uninstalled [-h] [-c CONFIG]
                           {add-recipe,rdeps,tag,genxcconfig,genlibfiles,check,list-packages,show-config,add-package,build,genvsprops,shell,run,cleanone,packageinfo,buildone,wipe,debug-packages,package,bootstrap,list,checkpackage,deps,gensdkshell,fetch-package,fetch}
                           ...
```

**Comment by superdump** [comment]
I think someone else reported that issue as well. Did you run a full update including the fetch-package, bootstrap and package commands?

**Comment by KensakuKOMATSU** [comment]
okay, I tried with the bootstrap already. I'll run from the starting point.

**Comment by KensakuKOMATSU** [comment]
succeeded to build!!! thx!
