### ISSUE TITLE
android: NativeCall crashes when website not available

### ISSUE THREAD

**Issue by sdroege** [EricssonResearch/openwebrtc-examples#173]
```
04-13 14:33:57.188 18398 18435 E EventSource: SSE: org.apache.http.conn.HttpHostConnectException: Connection to http://192.168.1.21:8080 refused
04-13 14:33:57.188 18398 18435 W System.err: org.apache.http.conn.HttpHostConnectException: Connection to http://192.168.1.21:8080 refused
04-13 14:33:57.189 18398 18435 W System.err: 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:193)
04-13 14:33:57.189 18398 18435 W System.err: 	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
04-13 14:33:57.189 18398 18435 W System.err: 	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
04-13 14:33:57.189 18398 18435 W System.err: 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:366)
04-13 14:33:57.189 18398 18435 W System.err: 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
04-13 14:33:57.189 18398 18435 W System.err: 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
04-13 14:33:57.189 18398 18435 W System.err: 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
04-13 14:33:57.189 18398 18435 W System.err: 	at com.ericsson.research.owr.examples.nativecall.SignalingChannel$1.run(SignalingChannel.java:94)
04-13 14:33:57.189 18398 18435 W System.err: 	at java.lang.Thread.run(Thread.java:818)
04-13 14:33:57.189 18398 18435 W System.err: Caused by: java.net.ConnectException: failed to connect to /192.168.1.21 (port 8080): connect failed: ECONNREFUSED (Connection refused)
04-13 14:33:57.193 18398 18435 W System.err: 	at libcore.io.IoBridge.connect(IoBridge.java:124)
04-13 14:33:57.193 18398 18435 W System.err: 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
04-13 14:33:57.193 18398 18435 W System.err: 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
04-13 14:33:57.193 18398 18435 W System.err: 	at java.net.Socket.connect(Socket.java:884)
04-13 14:33:57.193 18398 18435 W System.err: 	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:124)
04-13 14:33:57.193 18398 18435 W System.err: 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:149)
04-13 14:33:57.193 18398 18435 W System.err: 	... 8 more
04-13 14:33:57.193 18398 18435 W System.err: Caused by: android.system.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
04-13 14:33:57.194 18398 18435 W System.err: 	at libcore.io.Posix.connect(Native Method)
04-13 14:33:57.194 18398 18435 W System.err: 	at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
04-13 14:33:57.194 18398 18435 W System.err: 	at libcore.io.IoBridge.connectErrno(IoBridge.java:137)
04-13 14:33:57.194 18398 18435 W System.err: 	at libcore.io.IoBridge.connect(IoBridge.java:122)
04-13 14:33:57.194 18398 18435 W System.err: 	... 13 more
04-13 14:33:57.200 18398 18398 D NativeCall: stopping self-view
04-13 14:33:57.200 18398 18398 V OpenWebRTC: [3016]: got jobject[0x1005b7] from gobject[0xb3a2c858]
04-13 14:33:57.200 18398 18398 V OpenWebRTC: [3096]: got gobject[0xb3a2c858] from jobject[0xbef9011c]
04-13 14:33:57.200 18398 18398 V OpenWebRTC: [3096]: got gobject[0xb398f508] from jobject[0xbef9018c]
04-13 14:33:57.200 18398 18398 V OpenWebRTC: [3087]: got GObject[NULL] from jobject[null]
04-13 14:33:57.200 18398 18398 V OpenWebRTC: [3016]: got jobject[0x1005b7] from gobject[0xb3a2c858]
04-13 14:33:57.200 18398 18398 V OpenWebRTC: [3096]: got gobject[0xb3a2c858] from jobject[0xbef9011c]
04-13 14:33:57.200 18398 18398 V OpenWebRTC: [3096]: got gobject[0xb398f4b0] from jobject[0xbef9018c]
04-13 14:33:57.200 18398 18398 V OpenWebRTC: [3087]: got GObject[NULL] from jobject[null]
04-13 14:33:57.200 18398 18398 D AndroidRuntime: Shutting down VM
04-13 14:33:57.201 18398 18398 E AndroidRuntime: FATAL EXCEPTION: main
04-13 14:33:57.201 18398 18398 E AndroidRuntime: Process: com.ericsson.research.owr.examples.nativecall, PID: 18398
04-13 14:33:57.201 18398 18398 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void com.ericsson.research.owr.sdk.RtcSession.stop()' on a null object reference
04-13 14:33:57.201 18398 18398 E AndroidRuntime: 	at com.ericsson.research.owr.examples.nativecall.NativeCallExampleActivity.onDisconnect(NativeCallExampleActivity.java:338)
04-13 14:33:57.201 18398 18398 E AndroidRuntime: 	at com.ericsson.research.owr.examples.nativecall.SignalingChannel$1$1.run(SignalingChannel.java:120)
04-13 14:33:57.201 18398 18398 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
04-13 14:33:57.201 18398 18398 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-13 14:33:57.201 18398 18398 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
04-13 14:33:57.201 18398 18398 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
04-13 14:33:57.201 18398 18398 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-13 14:33:57.201 18398 18398 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-13 14:33:57.201 18398 18398 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-13 14:33:57.203   626 10720 W ActivityManager:   Force finishing activity com.ericsson.research.owr.examples.nativecall/.NativeCallExampleActivity

```

**Comment by Ankur1994a** [comment]
same for me . i am not able to make a connection with  http://demo.openwebrtc.org .
it shows an error E/EventSource: SSE: org.apache.http.conn.HttpHostConnectException: Connection to http://demo.openwebrtc.org refused.
please suggest me what to do fix this .
Thanks

**Comment by blakrin** [comment]
Same for me. i am not able to join a call it shows an error as 
`01-08 11:10:19.413 31115-31115/com.ericsson.research.owr.examples.nativecall E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                               Process: com.ericsson.research.owr.examples.nativecall, PID: 31115
                                                                                               java.lang.NullPointerException: Attempt to invoke interface method 'void com.ericsson.research.owr.sdk.RtcSession.stop()' on a null object reference
                                                                                                   at com.ericsson.research.owr.examples.nativecall.NativeCallExampleActivity.onDisconnect(NativeCallExampleActivity.java:331)
                                                                                                   at com.ericsson.research.owr.examples.nativecall.SignalingChannel$1$1.run(SignalingChannel.java:121)
                                                                                                   at android.os.Handler.handleCallback(Handler.java:815)
                                                                                                   at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                                   at android.os.Looper.loop(Looper.java:194)
                                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5631)
                                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
                                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
`
