### ISSUE TITLE
Android NativeCall app: getMediaDescription returns null

### ISSUE THREAD

**Issue by phetroy** [EricssonResearch/openwebrtc-examples#43]
01-27 18:34:09.181  24137-24137/com.ericsson.research.owr.examples.nativecall E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.ericsson.research.owr.examples.nativecall, PID: 24137
    java.lang.NullPointerException
            at com.ericsson.research.owr.examples.nativecall.PeerHandler.createMediaSession(PeerHandler.java:213)
            at com.ericsson.research.owr.examples.nativecall.PeerHandler.initialSetup(PeerHandler.java:205)
            at com.ericsson.research.owr.examples.nativecall.PeerHandler.handleSessionDescription(PeerHandler.java:268)
            at com.ericsson.research.owr.examples.nativecall.PeerHandler.onMessage(PeerHandler.java:115)
            at com.ericsson.research.owr.examples.nativecall.SignalingChannel$PeerChannel.onMessage(SignalingChannel.java:256)
            at com.ericsson.research.owr.examples.nativecall.SignalingChannel$PeerChannel.access$1000(SignalingChannel.java:219)
            at com.ericsson.research.owr.examples.nativecall.SignalingChannel.handleEvent(SignalingChannel.java:169)
            at com.ericsson.research.owr.examples.nativecall.SignalingChannel.access$900(SignalingChannel.java:52)
            at com.ericsson.research.owr.examples.nativecall.SignalingChannel$2.run(SignalingChannel.java:156)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5635)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by superdump** [comment]
@rugvip can probably answer this.

**Comment by Rugvip** [comment]
Do you have any steps to reproduce this, or does it seem to be random? Does it always happen when calling from the application? It looks like one or both of the local media descriptions are null.

I did just find a crash when calling to the application, when e.g. requesting video but not having the video box check in the application. Wasn't the same stack trace though.

**Comment by phetroy** [comment]
So the steps to reproduce are the following:

1. Open the nativecall app, enter the session id and tap "Join".
2. Use your web browser (chrome) and tap "Join"
3. Use your web browser (chrome) and tap "Call"
4. NativeCall app crashes with the reported exception.

**Comment by sanothay** [comment]
Hi, I am having exactly the same problem, is there anyway to solve this issue?

**Comment by sanothay** [comment]
Hi, further tested. When I connect to this URL: http://demo.openwebrtc.org:38080/, the app worked as expected. But when I connnected to my own server using server: channel_server.js. The app always crashed when I try to call by pressing call button. Anyone has an idea how to properly setup a private server to run openwebrtc?
